In [1]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [5]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

#                                       ARRAY CREATION using.....array()

In [7]:
my_list=[0,1,2,3,4,5] 
my_list

[0, 1, 2, 3, 4, 5]

In [9]:
import numpy
my_list=[0,1,2,3,4,5]
my_array=numpy.array(my_list)
my_array

array([0, 1, 2, 3, 4, 5])

In [11]:
type(my_array)

numpy.ndarray

#                                      Array creation using----arange()

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3.0)

array([0., 1., 2.])

In [15]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.arange(0,5)      #start=0,stop=4

array([0, 1, 2, 3, 4])

In [19]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
np.arange(20,10)       #1st argument<2nd argument then only we get o/p

array([], dtype=int32)

In [23]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [25]:
np.arange()         #Missed stop argument

TypeError: arange() requires stop to be specified.

In [27]:
np.arange(10,30,5)                    #1D array

array([10, 15, 20, 25])

In [29]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [31]:
np.arange(10,30,5,8)              #(start,stop,step).....3 Argumnets only

TypeError: Cannot interpret '8' as a data type

In [33]:
np.zeros(3)          #by default dtype is float...............system parameter tuning
                      #if we want we can tune by changing.........hyperparameter tuning

array([0., 0., 0.])

In [35]:
np.zeros(10)     #by default dtype is float...............system parameter tuning
                 #thats why ge

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros(3,dtype=int)          


array([0, 0, 0])

In [41]:
np.zeros((2,2))              #2D arry         


array([[0., 0.],
       [0., 0.]])

In [43]:
np.zeros((2,10))          #2D
                           #2-Rows,10-Columns


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.zeros((5,10))                       


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
np.zeros((5,10),dtype=int)             #hyperparameter tuning---chnge system parameter float(default) ---->int            


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [53]:
np.ones(3)

array([1., 1., 1.])

In [55]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [59]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [61]:
np.ones((5,4),dtype=int)          

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [63]:
np.twos((2,3                      #two() is not a function in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [65]:
np.three((2,3))                #three() is not a function in numpy

AttributeError: module 'numpy' has no attribute 'three'

In [67]:
rand(3,2)

NameError: name 'rand' is not defined

In [69]:
random.rand(3,2)


NameError: name 'random' is not defined

In [71]:
np.random.rand(5)   

array([0.34403389, 0.90960384, 0.95882187, 0.46797999, 0.89501625])

In [73]:
np.random.rand(5)   #in OTP we use this.evevry time the values are changing

array([0.16455319, 0.82270254, 0.1747201 , 0.0718609 , 0.49580713])

In [75]:
np.random.rand(5)     #again values are changing

array([0.36681792, 0.8278891 , 0.66533918, 0.53908616, 0.27358224])

In [77]:
np.rand(4)            #module missing

AttributeError: module 'numpy' has no attribute 'rand'

In [79]:
np.random.rand(4)   

array([0.33959331, 0.03679605, 0.00380929, 0.66110422])

In [86]:
np.random.rand(3,5)    #every time when we executing ....getting different values

array([[0.83366662, 0.43486474, 0.16863649, 0.05405602, 0.82147137],
       [0.8190892 , 0.60075306, 0.66049333, 0.92638506, 0.85218952],
       [0.84703522, 0.15614638, 0.52123055, 0.16084715, 0.74291565]])

In [88]:
np.random.randint(5)   

1

In [98]:
np.random.randint(4,6)       #the no's between 2 and 20.....2 is include
                                      #6......exclusive(don't cross 20)

5

In [100]:
np.random.randint(10,20,5)     #generate 5 numbers  in between 10 and 20
                               #10.....include,20.......exclude(don't cross 20)

array([12, 18, 11, 10, 17])

In [102]:
np.arange(1,13)                          #the reshapearray size shouldn't cross the original size 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [104]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [106]:
np.arange(1,13).reshape(5,4)         #the reshapearray size is crossing the original size 
                                    #of  array(original......np.arange(1,13)..... size=12)
                                    # reshape(5,4)=20 means size=20

ValueError: cannot reshape array of size 12 into shape (5,4)